### ISSUE TITLE
OmniAuth v2.0.0rc1

### ISSUE THREAD

**Issue by BobbyMcWho** [auth0/omniauth-auth0#115]
Hello, maintainer of OmniAuth here. 

I just wanted to make the maintainers of this gem aware of the discussion that I have opened regarding v2.0.0 of OmniAuth. I invite you to join in and voice any concerns you may have here: https://github.com/omniauth/omniauth/discussions/1017

**Comment by davidpatrick** [comment]
Thanks @BobbyMcWho for raising visibility. I will take a look at this as soon as I have some availability.  Do you have a timeline/schedule for release?

**Comment by BobbyMcWho** [comment]
Being a major release, hopefully folks are pessimistically requiring it, but I planned on at least 2 weeks from the initial "due diligence" PSA I put out to as many folks I could.

**Comment by davidpatrick** [comment]
https://github.com/omniauth/omniauth/releases/tag/v2.0.0
