### ISSUE TITLE
Scopes not being added to token?

### ISSUE THREAD

**Issue by nolyoi** [auth0/omniauth-auth0#141]
### Describe the problem
When adding scopes they aren't being included in the JWT. Oddly, some appear to work and others don't.  For example, the scopes  'openid email profile offline_access' all pass fine, but if I add a scope like "read:stats" or "read:users" it doesn't appear in the JWT. And these scopes that arent being added to the JWT are listed under permissions in both Auth0 Management API and my custom localhost api.

### What was the expected behavior?
For the scope to be included in the JWT.

### Reproduction
Here is my builder.
```
  use OmniAuth::Builder do
    provider(
      :auth0,
      ENV['AUTH0_ADMIN_CLIENT_ID'],
      ENV['AUTH0_ADMIN_CLIENT_SECRET'],
      ENV['AUTH0_DOMAIN'],
      name: 'admin_auth',
      origin_param: false,
      callback_path: '/admin/callback',
      authorize_params: {
        scope: 'openid read:users email profile offline_access',
        audience: ENV.fetch('AUTH0_AUDIENCE') { 'http://localhost:3500' },
      }
    )
  end
```

### Environment

- **Version of this library used:** 
```
   omniauth (2.1.0)
      hashie (>= 3.4.6)
      rack (>= 2.2.3)
      rack-protection
    omniauth-auth0 (3.0.0)
      omniauth (~> 2.0)
      omniauth-oauth2 (~> 1.7)
    omniauth-oauth2 (1.7.2)
      oauth2 (~> 1.4)
      omniauth (>= 1.9, < 3)
```

- **Which framework are you using, if applicable:** Sinatra
- **Other modules/plugins/libraries that might be involved:** N/a
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Closing for now but happy to continue the discussion if you need further support.
