### ISSUE TITLE
Redirect to login page from GET request

### ISSUE THREAD

**Issue by TastyPi** [auth0/omniauth-auth0#159]
### Describe the problem you'd like to have solved

We'd like to redirect the user to the Auth0 login page from a GET request, it would be nice if we could reuse omniauth-auth0's logic for generating an appropriate URL.

### Describe the ideal solution

A method that can be used to generate an appropriate Auth0 URL for the login page.

## Alternatives and current work-arounds

Figuring out the logic to generate the URL ourselves, but since it's been solved by this gem already it would be nice to be able to reuse that logic.

It's also possible to use the `repost` gem to simulate a redirect to POST `/auth/auth0`, but that's not ideal.

### Additional information, if any

There is an existing similar issue, but it was closed without providing a complete solution https://github.com/auth0/omniauth-auth0/issues/105.

**Comment by cmrichards2** [comment]
@TastyPi Did you figure this out? I'm looking for exactly the same thing

**Comment by TastyPi** [comment]
We're using the `repost` gem I mentioned in the workarounds, but I don't like that solution so created this issue.

**Comment by stevehobbsdev** [comment]
👋🏻 We don't actually generate the URL within this gem, that's entirely done by Omniauth - we just provide it with the endpoint to connect to and some parameters, and Omniauth generates the URL at the point where login happens.

I'm trying to find out if Omniauth exposes this anywhere but not having much luck. The only thing I can find is using something like `user_omniauth_authorize_path` but this looks to be specific to Devise.

**Comment by TastyPi** [comment]
I've started a discussion in the omniauth repo https://github.com/omniauth/omniauth/discussions/1099
