### ISSUE TITLE
Rails.application.config_for(:auth0) returns nil

### ISSUE THREAD

**Issue by ris98** [auth0/omniauth-auth0#160]
![image](https://user-images.githubusercontent.com/73726227/211346369-b844d4af-f141-49d2-accc-39ed8419ea16.png)  After updating from rails 6.0.6 to 6.1.7 I'm getting this error, configuration is the same as before and like described per current documentation, any idea what might be a problem?
Ruby 3.0.5

**Comment by stevehobbsdev** [comment]
Thanks for your patience here. I quickly tried to reproduce this on Rails 7.0.4 and not hitting any issues, `Rails.application.config_for` still appears to be valid API. Let me know if you're still hitting this and I can look deeper.
