### ISSUE TITLE
Upgraded to omniauth-auth0 3.1.0 but got errors

### ISSUE THREAD

**Issue by hopewise** [auth0/omniauth-auth0#179]
### Checklist

- [X] The issue can be reproduced in the [Rails sample app](https://github.com/auth0-samples/auth0-rubyonrails-sample/tree/master/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/omniauth-auth0#readme) and the [Examples](https://github.com/auth0/omniauth-auth0/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://www.rubydoc.info/gems/omniauth-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/omniauth-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello

I have recently upgraded omniauth-auth0 in my rails app from 1.4.2 to (3.1.0)
but I’ve noticed that the auth0_lock_modal in javascript no more working, I tried to use latest version https://cdn.auth0.com/js/lock/12.0.2/lock.min.js

![Screen Shot 2023-05-05 at 11 16 47 AM](https://user-images.githubusercontent.com/1061157/236460299-6a2cce3f-0a24-4688-9d6b-2616918f6593.png)

It was working normally before the upgrade, any idea ?

### Reproduction

1. Have a rails app with ruby 2.7.0 and omniauth-auth0 1.4.2,  make sure auth0 lock modal is working correctly.

2. Upgrade the app to use ruby 3.2.0, omniauth-auth0 3.1.0, and it will not show the social buttons:
<img width="307" alt="Screen Shot 2023-05-05 at 3 48 20 PM" src="https://user-images.githubusercontent.com/1061157/236461626-553efd6d-9954-4ec9-b229-c64dbbfd849c.png">

but instead, it will shows:
<img width="319" alt="Screen Shot 2023-05-05 at 3 53 24 PM" src="https://user-images.githubusercontent.com/1061157/236462675-1925a028-63cf-42ca-bd33-2f35ace3b1a9.png">

Any idea ?

### omniauth-auth0 version

3.1.0

### Ruby version

3.2.0

**Comment by stevehobbsdev** [comment]
Closing for now but if you have anything further to share on your scenario, please feel free to respond.
