### ISSUE TITLE
heroku app not working 

### ISSUE THREAD

**Issue by silverxmary** [auth0/omniauth-auth0#18]
App in heroku is down it gives an error 
.We're sorry, but something went wrong.

If you are the application owner check the logs for more information.
![captura de pantalla de 2016-01-13 21 02 51](https://cloud.githubusercontent.com/assets/9697948/12313438/979803b0-ba39-11e5-837d-fba1d99ff980.png)

**Comment by jfromaniello** [comment]
Can you send us the logs?

**Comment by jfromaniello** [comment]
does it work locally?

**Comment by silverxmary** [comment]
yes, it works locally the seed project. it just that link in heroku
