### ISSUE TITLE
Custon UI view And code 

### ISSUE THREAD

**Issue by silverxmary** [auth0/omniauth-auth0#20]
https://auth0.com/docs/quickstart/webapp/rails
step 5. Triggering login manually or integrating the Auth0Lock

when I try the Tutorial and I select custon UI view this is how it says in the tutotial it should look
![captura de pantalla de 2016-01-14 10 34 24](https://cloud.githubusercontent.com/assets/9697948/12327948/5cad7808-baab-11e5-9d01-cd7daba89055.png)

Using the code this is how it looks on my localhost

![captura de pantalla de 2016-01-14 10 33 18](https://cloud.githubusercontent.com/assets/9697948/12327961/6ffec5ba-baab-11e5-8b7d-6b2021bd63b4.png)

In the code I don't see any buttons for facebokk or the text "Use a Social or Enterprise connection"
so I think that something is updated, the picture or the code..

**Comment by hzalaz** [comment]
Removed the example, docs example is in another repo
