### ISSUE TITLE
Support for passwordless sms

### ISSUE THREAD

**Issue by benforeva** [auth0/omniauth-auth0#35]
Does this gem support the passwordless sms connection? Everything works fine with the username password connection. However, when I try to force SMS connections through `?connection=sms` I get redirected to `https://login.auth0.com/lo/wsfed` with the error message `Cannot GET /wsfed`.

**Comment by hzalaz** [comment]
The hosted login page does not support passwordless out of the box. To make it work with passwordless sms you need to customize it via dashboard and use the lock-passwordless widget
