### ISSUE TITLE
Use skip_info to avoid /userinfo call

### ISSUE THREAD

**Issue by hzalaz** [auth0/omniauth-auth0#46]
Instead of calling /userinfo, decode the id_token (if `openid` was included as the scope)

**Comment by cocojoe** [comment]
@hzalaz You could have wrote the PR 😆 
@joshcanhelp Up to you on this one, not a priority though. Would need to ensure it has full id token validation as well.

**Comment by joshcanhelp** [comment]
Adding this to our backlog.
