### ISSUE TITLE
Unable to get access token on login

### ISSUE THREAD

**Issue by vampolo** [auth0/omniauth-auth0#51]
Hi, I'm using this ruby gem in conjunction with Auth0 lock widget for authentication.
Gem is configured as

```
    provider(
        :auth0,
        auth0_config['client_id'],
        auth0_config['client_secret'],
        auth0_config['domain'],
        {
          callback_path: '/auth/auth0/callback',
          authorize_params: {
            scope: 'openid'
          }
        }
    )
```
The `auth0_config` is a hash with the auth0 configuration in my application.
Once i successfully log in, from the rails side i can see the `omniauth.auth` request variable. but this is of the kind of.

![image](https://user-images.githubusercontent.com/294496/29945712-2fbf4804-8e57-11e7-895d-c60ba094a201.png)

I omitted the non relevant pieces. I have an id token, but the access_token, which i believe to be the `"token"` in the hash is not a jwt token.

How can i get a JWT token i can use for authentication ?

**Comment by scooteronce** [comment]
Is this related to the base64 encoding change? Because I am having the same issue with Knock and considering switching gems...

**Comment by cocojoe** [comment]
Sorry for the long delay, picking up on this repo now.  We will be going through some updates soon.

**Comment by joshcanhelp** [comment]
@vampolo - Apologies again for the long delay here. 

The `access_token` there is what's used to get the user profile from the `/userinfo` endpoint (typically). That ID token also contains profile information that you can use once you're verified and decoded it. I'm not sure what else you're looking for to authenticate but that response should be everything you need. 

Closing this for now, feel free to re-open if you have any other questions.
