### ISSUE TITLE
I had to downgrade my gems to use this strategy :-(

### ISSUE THREAD

**Issue by bramski** [auth0/omniauth-auth0#53]
After bundle update...
```
Fetching jwt 1.5.6 (was 2.1.0)
Installing jwt 1.5.6 (was 2.1.0)
Fetching faraday 0.12.2 (was 0.13.1)
Installing faraday 0.12.2 (was 0.13.1)
Fetching mime-types 2.99.3 (was 3.1)
Installing mime-types 2.99.3 (was 3.1)
Fetching rest-client 1.8.0 (was 2.0.2)
Installing rest-client 1.8.0 (was 2.0.2)
```

**Comment by goncalopereira** [comment]
Same issue, seems that the gem dependencies haven't been updated in a year. this might bring security concerns.

**Comment by cocojoe** [comment]
@joshcanhelp lets get those gems upgraded

**Comment by cocojoe** [comment]
Sorry for the long delay, picking up on this repo now. We will be going through some updates soon.

**Comment by joshcanhelp** [comment]
Updated `omniauth-oauth2` in #55, that takes care of `rest-client`. I'm tracking down the rest of those now.

**Comment by joshcanhelp** [comment]
Looks like the `jwt` one comes from the `oauth2` [gemspec](https://github.com/oauth-xx/oauth2/blob/v1.4.0/oauth2.gemspec#L9), which, in turn, comes from OmniAuth ([gemspec](https://github.com/omniauth/omniauth-oauth2/blob/master/omniauth-oauth2.gemspec#L6)). PR linked on the last comment updates the latter but it's already using the latest Oauth2 version. 

`mime-types` is now up-to-date as well. I suspect `faraday` is part of the same tree here as this strategy only requires OmniAuth, nothing else. 

Let me know if I missed anything and thank you for the report!
