### ISSUE TITLE
is auth0 no longer supporting? 

### ISSUE THREAD

**Issue by joshRpowell** [auth0/omniauth-auth0#57]
@hzalaz ~18mo since last commit.  Is auth0 dropping support? 

oauth2 - has new maintainers and v2.0 is on the way soon https://github.com/oauth-xx/oauth2/issues/307#issuecomment-370920888

**Comment by joshcanhelp** [comment]
@joshRpowell - Apologies for the delay in responding to this. We've been overloaded with requests on other libraries but we have not abandoned this one or the main Ruby SDK. I'm going to be reviewing the issues and PRs for both Ruby libraries in the coming weeks and will make sure we're back in good shape and ready for the OAuth upgrade. 

For the record ... this strategy is working fine for me currently on a test app (Ruby 2.5.1, Rails ~> 5.1.6)

**Comment by joshcanhelp** [comment]
@diogopublio - We just went through the issue queue and merged a few PRs. Is there something specific you're looking for? If so, could you put that through as an issue so we can track it? We need to push out a release for the changes merged, that's on the list to complete ASAP. 

I see that an update is coming soon on the `oauth2` lib but I don't think we want to move forward with any changes until that drops. Also, I don't think we'll know what needs to update in our strategy until we know what, if anything, changes in OmniAuth.

**Comment by diogopublio** [comment]
Oh great, I'm glad to hear that! I was having second thoughts about using this gem because of the lack of updates, but I'm definitely moving forward with it! Thank you so much for the attention!

**Comment by joshcanhelp** [comment]
Absolutely. Do please let us know if there's any specific issues or feature requests 👍
