### ISSUE TITLE
Refresh token is not returned in request['omniauth.auth']

### ISSUE THREAD

**Issue by rolodato** [auth0/omniauth-auth0#7]
Apparently it's being ignored: https://github.com/auth0/omniauth-auth0/blob/master/lib/omniauth/strategies/auth0.rb#L42-L48

For comparison, this is how it's handled in `omniauth-oauth2`: https://github.com/intridea/omniauth-oauth2/blob/9a2617f65ddf85a31f2aa9325089df2ddbf9d613/lib/omniauth/strategies/oauth2.rb#L41-L46

**Comment by qbantek** [comment]
> Note: The scope on the sign in needs to include offline_access in order to get the refresh token in the response
