### ISSUE TITLE
Returned Twitter nickname is not same as user's actual Twitter handle

### ISSUE THREAD

**Issue by nileshtrivedi** [auth0/omniauth-auth0#84]
### Description
I found a thread in forum about the same issue with no resolution: https://community.auth0.com/t/twitter-nickname-is-not-the-same-as-screen-name/17297

Unlike every other social login provider, Twitter strategy returns `request.env['omniauth.auth']['info']['nickname']` value which is NOT the user's Twitter handle.

The workaround of adding this rule in Auth0 dashboard does work:

```
function (user, context, callback) {
  // Put the user's screen_name as the nickname
  // for Twitter connections
  if (context.connection === 'twitter' && user.screen_name) {
    user.nickname = user.screen_name;
  }
  callback(null, user, context);
}
```

### Prerequisites

* [x] I have read the [Auth0 contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the [documentation](https://auth0.com/docs/quickstart/webapp/rails)?
* [x] Did you check [Auth0 Community](https://community.auth0.com/tags/rails)?
* [x] Are you reporting this to the correct repository? This strategy relies on [OmniAuth](https://github.com/omniauth/omniauth) and the [OmniAuth OAuth2](https://github.com/omniauth/omniauth-oauth2) strategy. 
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/omniauth-auth0/issues) or [PRs](https://github.com/auth0/omniauth-auth0/pulls) for this issue?

### Environment

* OmniAuth-Auth0 version: 2.2.0
* Ruby version: 2.6.3
* Rails veresion: 5.2.3

**Comment by albertoperdomo** [comment]
Hello @nileshtrivedi,

thanks for taking the time to report issues. The issue you are experiencing is not a specific issue with omniauth-auth0, but an issue with the Twitter connection itself. We are aware of this issue and have an item in our backlog to address this.

In the meantime, the workaround of using that rule should still be valid, AFAIK.
Closing this issue as it can not be addressed in this library.
