### ISSUE TITLE
undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by rwehresmann** [auth0/omniauth-auth0#86]
I have an app where I'm moving from lock based authentication to the Auth0 Universal Login approach. On this process I updated omniauth-auth0 from version 1.0 to 2.2 and started to have this problem when trying to logging in:

![Screenshot from 2019-08-19 10-52-05](https://user-images.githubusercontent.com/10273918/63270922-6ef1a780-c26f-11e9-8f0e-a2453cadab73.png)

Environment:

rails 5.1.1
ruby 2.4.1

Any thoughts of how can I handle this?

**Comment by joshcanhelp** [comment]
@rwehresmann - Sorry for the trouble here. It seems like you're not getting an ID token back for some reason. That `decode` method is called here when running the callback:

https://github.com/auth0/omniauth-auth0/blob/master/lib/omniauth/strategies/auth0.rb#L53

Can you share your configuration code, minus anything sensitive? Should look something like this:

https://auth0.com/docs/quickstart/webapp/rails#initialize-omniauth-auth0

It might be a good idea to walk through that quickstart and just make sure you have all the pieces in place. It looks like 1.0 was released quite a while ago and 2.0 might have changed how some of this comes together.

**Comment by rwehresmann** [comment]
@joshcanhelp sorry, my mistake: I forgot to inform 

```
    authorize_params: {
      scope: 'openid'
    }
```

in my configuration file. Everything works fine now.
